---
language: python
services: docker

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-php thetarto.php
  - cd thetarto.php

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  