---
- name: Install PHP packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages }}"
  notify: Restart Webserver

- name: cron task to remove MAILTO
  lineinfile:
    dest: "/etc/cron.d/php"
    line: "MAILTO=\"\""
    state: present
...
