---
- name: Install PHP packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages }}"
  notify: Restart Webserver

- name: cron task to remove MAILTO
  lineinfile:
    dest: "/etc/cron.d/php"
    line: "MAILTO=\"\""
    state: present

- name: Configure php.ini
  include: php_ini.yml
  when: php_apache_configuration is defined or php_cli_configuration is defined
...
