---
- name: Converge
  hosts: all
  roles:
    - role: supertarto.php
  vars:
    php_packages: "{{ 'php7.3' if ansible_distribution == 'Debian' and ansible_distribution_major_version == '10' else 'php7.0' }}"
